[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "tree-copula-vae"
version = "0.1.0"
description = "Scaffold for the tree-copula VAE project"
readme = "README.md"
requires-python = "==3.8"
dependencies = [
  "torch",
  "lightning",
  "torchvision",
  "numpy",
  "scipy",
  "networkx",
  "statsmodels",
  "scikit-learn",
  "tqdm",
  "pyro-ppl",
  "dgl",
  "mixedvines",
  "pyrallis"
]

[project.optional-dependencies]
dev = ["pytest"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["tree_copula_vae*"]
