training_params:
  max_epochs: 50
  check_val_every_n_epoch: 1
  batch_size: 128
  hidden_dim: 3
  beta: 1.0
  lr: 0.005
  betas: [0.95, 0.999]
  name: ScrewDSprites
  logger_save_dir: /data/yarden/experiments/
  seed: 1265
data:
  data_dir: /home/yarden/TreeCopulaNew/data/
  batch_size: 128
  pin_memory: true
  num_workers: 4
  tolerance: 0.15
model:
  model_type: COPULA_VAE
  latent_dim: 3
  learning_rate: 0.005
  kl_coeff: 0.0
  K_eval: 50
  K_test: 512
  decoder_rank: 0
  use_nf_prior: false
  use_copula_decoder: false
  pair_copula_type: BiVariateStudentTCopula
  start_temperature: 2.0
  inject_noise: false
  use_copula_prior: false
callbacks:
  kl_annealing:
    warmup_epochs: 10
    max_beta: 1.0
  anneal_attribute:
    start_value: 2.0
    end_value: 0.1
    mode: two_phase
    warmup_frac: 0.2
  model_checkpoint:
    monitor: val/elbo
    mode: max
    save_top_k: 1
    save_last: true
  learning_rate_monitor: true
trainer:
  accelerator: gpu
  devices: [2]
  precision: 32
  gradient_clip_val: 0.5
  deterministic: false
  log_every_n_steps: 50
  min_epochs: 1
  detect_anomaly: false
checkpoint:
  resume_training: false
  monitor_in_same_experiment: false
  ckpt_dir_format: /data/yarden/experiments/checkpoints/{}/tree_vae_dsprite/last.ckpt
  run_id: null
